export enum UserAttributes {
  profile = 'profile',
  address = 'address',
  birthdate = 'birthdate',
  gender = 'gender',
  preferred_username = 'preferred_username',
  updated_at = 'updated_at',
  website = 'website',
  picture = 'picture',
  sub = 'sub',
  phone_number = 'phone_number',
  phone_number_verified = 'phone_number_verified',
  zoneinfo = 'zoneinfo',
  locale = 'locale',
  email = 'email',
  email_verified = 'email_verified',
  given_name = 'given_name',
  family_name = 'family_name',
  middle_name = 'middle_name',
  name = 'name',
  nickname = 'nickname',
  displayName = 'custom:displayName',
  handle = 'custom:handle',
  onboardingComplete = 'custom:onboardingComplete',
}
